// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqpoZf50sFrZDoQkz9CaEHsoFZcubsBtA',
    appId: '1:886734057478:web:7547a93f642c9519059387',
    messagingSenderId: '886734057478',
    projectId: 'shoe-shop-35632',
    authDomain: 'shoe-shop-35632.firebaseapp.com',
    storageBucket: 'shoe-shop-35632.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-kmbBZpm2_skYhJA9LKMtht4zDpDJfio',
    appId: '1:886734057478:android:0a8313bf969ea407059387',
    messagingSenderId: '886734057478',
    projectId: 'shoe-shop-35632',
    storageBucket: 'shoe-shop-35632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fnrP9I30i9JUHv10M7IqJSL8eSPxHro',
    appId: '1:886734057478:ios:89b9f7bd706af44b059387',
    messagingSenderId: '886734057478',
    projectId: 'shoe-shop-35632',
    storageBucket: 'shoe-shop-35632.firebasestorage.app',
    iosBundleId: 'com.example.shoeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fnrP9I30i9JUHv10M7IqJSL8eSPxHro',
    appId: '1:886734057478:ios:89b9f7bd706af44b059387',
    messagingSenderId: '886734057478',
    projectId: 'shoe-shop-35632',
    storageBucket: 'shoe-shop-35632.firebasestorage.app',
    iosBundleId: 'com.example.shoeShop',
  );
}
